// <auto-generated />
using Bif4.Schiermayer.MyApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Bif4.Schiermayer.MyApp.Migrations
{
    [DbContext(typeof(LvDbContext))]
    [Migration("20180407110308_CreateSchema")]
    partial class CreateSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Bif4.Schiermayer.MyApp.Lehrveranstaltung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<int>("ECTS");

                    b.Property<string>("Exam");

                    b.Property<string>("Fullname");

                    b.Property<string>("Lector");

                    b.Property<string>("Moodle");

                    b.HasKey("ID");

                    b.ToTable("Lehrveranstaltungen");
                });
#pragma warning restore 612, 618
        }
    }
}
